<div class="main-container container-fluid">
    <a class="menu-toggler" id="menu-toggler" href="#">
        <span class="menu-text"></span>
    </a>


    <aisde>
        <?php echo $this->render('nav.phtml') ?>  
    </aside>


    <div class="main-content">  
<!--            <nav>
                <?php //echo $this->render('breadcrumbs.phtml') ?>
            </nav>-->
            <div class="page-content">
                <div class="row-fluid">
                    <div class="span12">
                        <section>
                        <!--PAGE CONTENT BEGINS-->
                        <?php echo $this->layout()->content; ?> 
                        <!--PAGE CONTENT ENDS-->
                        </section>
                    </div><!--/.span-->
                </div><!--/.row-fluid-->
            </div><!--/.page-content-->
    </div><!--/.main-content-->
</div><!--/.main-container-->

