<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
    <i class="icon-double-angle-up icon-only bigger-110"></i>
</a>

<!--basic scripts-->

<!--[if !IE]>-->

<script src="<?php echo $this->baseUrl;?>/googleapis/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

<!--<![endif]-->

<!--[if IE]>
<script src="<?php echo $this->baseUrl;?>/googleapis/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]>-->

<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->baseUrl;?>/googleapis/ajax/libs/jquery/2.0.3/jquery.min.js'>" + "<" + "/script>");
</script>

<!--<![endif]-->

<!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='<?php echo $this->baseUrl;?>/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if ("ontouchend" in document)
        document.write("<script src='http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js'>" + "<" + "/script>");
</script>
<script src="<?php echo $this->baseUrl;?>/assets/js/bootstrap.min.js"></script>

<!--page specific plugin scripts-->

<!--ace scripts-->

<script src="<?php echo $this->baseUrl;?>/assets/js/ace-elements.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/assets/js/ace.min.js"></script>

<!--inline scripts related to this page-->
 <?php echo $this->headScript() ?>
<script type="text/javascript">

$(function() {
$(".chzn-select").chosen(); 
});
//chosen plugin inside a modal will have a zero width because the select element is originally hidden
				//and its width cannot be determined.
				//so we set the width after modal is show
					
					$(this).find('.chzn-container').each(function(){
						$(this).find('a:first-child').css('width' , '200px');
						$(this).find('.chzn-drop').css('width' , '210px');
						$(this).find('.chzn-search input').css('width' , '200px');
					});
				
</script>
