<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
    <i class="icon-double-angle-up icon-only bigger-110"></i>
</a>

<!--basic scripts-->

<!--[if !IE]>-->

<script src="<?php echo $this->baseUrl;?>/googleapis/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

<!--<![endif]-->

<!--[if IE]>
<script src="<?php echo $this->baseUrl;?>/googleapis/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]>-->

<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->baseUrl;?>/googleapis/ajax/libs/jquery/2.0.3/jquery.min.js'>" + "<" + "/script>");
</script>

<!--<![endif]-->

<!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='<?php echo $this->baseUrl;?>/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if ("ontouchend" in document)
        document.write("<script src='http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js'>" + "<" + "/script>");
</script>
<script src="<?php echo $this->baseUrl;?>/assets/js/bootstrap.min.js"></script>

<!--page specific plugin scripts-->
 <script type="text/javascript" src="<?php echo $this->baseUrl;?>/assets/js/prettify.js"></script>
    
    <script src="http://localhost/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
    <script src="http://localhost/bootstrap-modal/js/bootstrap-modal.js"></script>
<!--ace scripts-->

<script src="<?php echo $this->baseUrl;?>/assets/js/ace-elements.min.js"></script>
<script src="<?php echo $this->baseUrl;?>/assets/js/ace.min.js"></script>


<!--inline scripts related to this page-->
 <?php echo $this->headScript() ?>

<div id="ajax-modal" class="modal hide fade" ></div>   

<script type="text/javascript">

$(function() {
$(".chzn-select").chosen({width: "100%"}); 

$('.input-mask-date').mask('99/99/9999');

$('.date-picker').datepicker().next().on(ace.click_event, function(){
                                        $(this).prev().focus();
                                });
                                
    var oTable1 = $('#sample-table-2').dataTable( {
        "aoColumns": [
        { "bSortable": true },
         null, null, null,null, null, null,
          { "bSortable": false }
    ] } );


    $('table th input:checkbox').on('click' , function(){
            var that = this;
            $(this).closest('table').find('tr > td:first-child input:checkbox')
            .each(function(){
                    this.checked = that.checked;
                    $(this).closest('tr').toggleClass('selected');
            });

    });
    
    $('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});
				function tooltip_placement(context, source) {
					var $source = $(source);
					var $parent = $source.closest('table')
					var off1 = $parent.offset();
					var w1 = $parent.width();
			
					var off2 = $source.offset();
					var w2 = $source.width();
			
					if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
					return 'left';
				}
                                
      
            var $modal = $('#ajax-modal');

            $('[data-toggle="modal-ajax"]').on('click', function(){
                var $url = $(this).attr('href');
              // create the backdrop and wait for next modal to be triggered
              $('body').modalmanager('loading');
              $('.progress').addClass('progress-info');
             
                 $modal.load($url, '', function(){
                  $modal.modal();
                });
             
            });

           
           


});

</script>
