<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a href="#" class="brand">
                <small>
                    <i class="icon-leaf"></i>
                    AGV - <?php echo $this->headTitulo ?>
                </small>
            </a><!--/.brand-->
            <ul class="nav ace-nav pull-right">			
                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="<?php echo $this->baseUrl;?>/assets/avatars/user.jpg" alt="Jason's Photo" />
                        <span class="user-info">
                            <small>Usuario,</small>
                           <?php echo $this->infoUsuario->usuario ?>
                        </span>

                        <i class="icon-caret-down"></i>
                    </a>

                    <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">

                        <li>
                            <a href="#">
                                <i class="icon-user"></i>
                                Mi Cuenta
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="<?php echo $this->baseUrl;?>/autenticacion/login/logout">
                                <i class="icon-off"></i>
                                Salir
                            </a>
                        </li>
                    </ul>
                </li>
            </ul><!--/.ace-nav-->
        </div><!--/.container-fluid-->
    </div><!--/.navbar-inner-->
</div>
