<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        
        <title>AGV | <?php echo $this->headTitulo ?> </title>
        
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!--basic styles-->
        <link href="<?php echo $this->baseUrl;?>/cassets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="<?php echo $this->baseUrl;?>/assets/css/bootstrap-responsive.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl;?>/assets/css/font-awesome.min.css" />
        <!--[if IE 7]>
          <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
        <![endif]-->

        <!--fonts-->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />
        <!--ace styles-->
        <link rel="stylesheet" href="/assets/css/ace.min.css" />
        <link rel="stylesheet" href="assets/css/ace-responsive.min.css" />
        <!--link rel="stylesheet" href="/agv/public/assets/css/ace-skins.min.css" /-->

        <!--[if lte IE 8]>
          <link rel="stylesheet" href="/agv/public/assets/css/ace-ie.min.css" />
        <![endif]-->

    </head>
    <body>
        <header> 
            <?php echo $this->render('header.phtml') ?>
        </header>   
        <section>
             <?php echo $this->render('content.phtml') ?>  
        </section>
        <footer>
             <?php echo $this->render('footer.phtml') ?> 
        </footer>
    </body>
    