<div class="sidebar" id="sidebar">
    <div class="sidebar-shortcuts" id="sidebar-shortcuts">

    </div><!--#sidebar-shortcuts-->

    <ul class="nav nav-list">
        <li>
            <a href="<?php echo $this->baseUrl;?>/">
                <i class="icon-dashboard"></i>
                <span class="menu-text">Inicio </span>
            </a>
        </li>
        <li>
            <a href="#" class="dropdown-toggle">
                <i class="icon-tags"></i>
                <span class="menu-text">Ventas</span>
                <b class="arrow icon-angle-down"></b>
            </a>
            <ul class="submenu">
                <li>
                    <a href="#" class="dropdown-toggle">
                        <i class="icon-shopping-cart"></i>
                        Pedidos
                        <b class="arrow icon-angle-down"></b>
                    </a>
                    <ul class="submenu">
                        <li>
                            <a href="<?php echo $this->baseUrl;?>/ventas/pedidos/nuevo">
                                <i class="icon-plus"></i>
                               Nuevo Pedido
                            </a>
                        </li>

                        <li>
                            <a href="<?php echo $this->baseUrl;?>/ventas/pedidos/">
                                <i class="icon-eye-open"></i>
                                Ver Pedidos
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
      
    </ul><!--/.nav-list-->

    <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left"></i>
    </div>
</div>