<form id="validation-form" method="post" action="<?php echo $this->formCrearCliente->getAction(); ?>">
    <div  tabindex="-1">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="blue bigger">Agregar Cliente</h4>
        </div>
        
        <div class="modal-body overflow-visible">

            <div class="row-fluid">

                <div class="span12">
                    <div class="control-group">
                        <label for="form-field-select-3">Razon Social</label>

                        <div class="controls">
                            <?php echo $this->formCrearCliente->descripcion; ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span3">                
                    <div class="control-group">
                        <label class="control-label" for="form-field-first">Rif : <small class="text-error">J9999999-9</small></label>

                        <div class="controls input-prepend">
                            <span class="add-on">
                                <i class="icon-info-sign"></i>
                            </span>
                            <?php echo $this->formCrearCliente->rif; ?>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="modal-footer">
            <button style="margin-top: 34px;" class="btn btn-small" data-dismiss="modal">
                <i class="icon-remove"></i>
                Cancelar
            </button>
            
            
            
            <button style="margin-top: 34px;" class="btn btn-small btn-primary">
                <i class="icon-ok"></i>
                Guardar Cliente
            </button>
        </div>
    </div>
</form>

<?php echo $this->headScript() ?>

<script type="text/javascript">
    $(function() {
    
      $.mask.definitions['J'] = "[JVjv]";
      $('#rif').mask('J99999999-9');
      
      $('#validation-form').validate({
            errorElement: 'span',
            errorClass: 'help-inline',
            focusInvalid: false,
            rules: {
               
                descripcion: {
                    required: true
                },
                rif: {
                    required: true
                },
               
            },
            messages: {
                descripcion: {
                    required: "Debe Indicar Razon Social",
                },
                rif: {
                    required: "Debe Indicar Rif Valido",
                },
               
            },
            invalidHandler: function(event, validator) { //display error alert on form submit   
                $('.alert-error', $('.login-form')).show();
            },
            highlight: function(e) {
                $(e).closest('.control-group').removeClass('success').addClass('error');
            },
            success: function(e) {
                $(e).closest('.control-group').removeClass('error').addClass('success');
                $(e).remove();
            },          
            submitHandler: function(form) {
               // alert('submit');
                form.submit();
                $('.btn').attr("disabled", "disabled");
            },
            invalidHandler: function(form) {
            }
        });
   
    })
</script>