<form id="form-agregararticulo" method="post" action="/ventas/pedidos/agregararticulo/" >
    <div  tabindex="-1">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="blue bigger">Please fill the following form fields</h4>
        </div>

        <div class="modal-body overflow-visible">
            <div class="row-fluid">

                <div class="vspace"></div>

                <div class="span7">

                    <div class="control-group">
                        <label for="form-field-select-3">Location</label>

                        <div class="controls">
                            <select class="chzn-select" data-placeholder="Choose a Country...">
                                <option value=""></option>
                                <option value="AL">Alabama</option>
                                <option value="AK">Alaska</option>
                                <option value="AZ">Arizona</option>
                                <option value="AR">Arkansas</option>               
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="form-field-select-3">Articulo</label>

                        <div class="controls">
                            <?php echo $this->formArticulos->articulo; ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="form-field-username">Username</label>
                        <?php echo $this->formArticulos->idpedido; ?>
                        <div class="controls">

                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="form-field-first">Cantidad</label>

                        <div class="controls">
                            <br/>
                            <?php echo $this->formArticulos->cantidad; ?>

                            <?php echo $this->formArticulos->desc; ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button class="btn btn-small" data-dismiss="modal">
                <i class="icon-remove"></i>
                Cancel
            </button>

            <button class="btn btn-small btn-primary">
                <i class="icon-ok"></i>
                Save
            </button>
        </div>
    </div>

    
<?php echo $this->headScript() ?>
    
 <script type="text/javascript">

$(function() {
    $(".chzn-select").chosen({width: "100%"}); 
    
    $('#form-agregararticulo').validate({
                    errorElement: 'span',
                    errorClass: 'help-inline',
                    focusInvalid: false,
                    rules: {
                       
                        articulo: {
                            required: true
                        },
                        cantidad: {
                            required: true,
                            num: true
                        },
                        phone: {
                            required: true,
                            phone: 'required'
                        },
                        
                        agree: 'required'
                    },
                    messages: {
                        articulo: {
                            required: "Debe Selecionar un arcticulo",
                            
                        },
                        cantidad: {
                            required: "es obligatorio",
                            num: "Cantidad distinta de cero",
                            
                        },
                        password: {
                            required: "Please specify a password.",
                            minlength: "Please specify a secure password."
                        },
                        subscription: "Please choose at least one option",
                        gender: "Please choose gender",
                        agree: "Please accept our policy"
                    },
                    invalidHandler: function(event, validator) { //display error alert on form submit   
                        $('.alert-error', $('.login-form')).show();
                    },
                    highlight: function(e) {
                        $(e).closest('.control-group').removeClass('info').addClass('error');
                    },
                    success: function(e) {
                        $(e).closest('.control-group').removeClass('error').addClass('info');
                        $(e).remove();
                    },
                    errorPlacement: function(error, element) {
                        if (element.is(':checkbox') || element.is(':radio')) {
                            var controls = element.closest('.controls');
                            if (controls.find(':checkbox,:radio').length > 1)
                                controls.append(error);
                            else
                                error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                        }
                        else if (element.is('.select2')) {
                            error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                        }
                        else if (element.is('.chzn-select')) {
                            error.insertAfter(element.siblings('[class*="chzn-container"]:eq(0)'));
                        }
                        else
                            error.insertAfter(element);
                    },
                    submitHandler: function(form) {
                    },
                    invalidHandler: function(form) {
                    }
                });
    
});
    </script>  
    
</form>
<!--PAGE CONTENT ENDS-->