<form id="validation-form" method="post" action="/ventas/pedidos/editar/id/20">

    <div  tabindex="-1">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="blue bigger">Please fill the following form fields</h4>
        </div>

        <div class="modal-body overflow-visible">
            <div class="row-fluid">

                <div class="vspace"></div>

                <div class="span7">

                    <div class="control-group">
                        <label class="control-label" for="state">State</label>

                        <div class="controls">
                            <span class="span12">
                                <select id="state" name="state" class="select2" data-placeholder="Click to Choose...">
                                    <option value=""></option>
                                    <option value="AL">Alabama</option>
                                    <option value="AK">Alaska</option>
                                    <option value="AZ">Arizona</option>
                                    <option value="AR">Arkansas</option>
                                    <option value="CA">California</option>
                                    <option value="CO">Colorado</option>
                                    <option value="CT">Connecticut</option>

                                </select>
                            </span>
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="form-field-select-3">Articulo</label>

                        <div class="controls">
                            <?php echo $this->formArticulos->articulo; ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="form-field-username">Username</label>
                        <?php echo $this->formArticulos->idpedido; ?>
                        <div class="controls">

                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="form-field-first">Cantidad</label>

                        <div class="controls">
                           <input type="text" class="input-mini" id="spinner3" />
                            <?php echo $this->formArticulos->cantidad; ?>

                            <?php echo $this->formArticulos->desc; ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button class="btn btn-small" data-dismiss="modal">
                <i class="icon-remove"></i>
                Cancel
            </button>

            <button class="btn btn-small btn-primary">
                <i class="icon-ok"></i>
                Save
            </button>
        </div>
    </div>
</form>


<?php echo $this->headScript() ?>
<!--inline scripts related to this page-->

<script type="text/javascript">
    $(function() {

        $(".chzn-select").chosen({width: "100%"});
        
        $('#spinner3').ace_spinner({value:1,min:1,max:1000,step:1, icon_up:'icon-plus', icon_down:'icon-minus', btn_up_class:'btn-success' , btn_down_class:'btn-danger'});

        $(".select2").css('width', '100%').select2({allowClear: true})
                .on('change', function() {
            $(this).closest('form').validate().element($(this));
        });

        //documentation : http://docs.jquery.com/Plugins/Validation/validate

        $('#validation-form').validate({
            errorElement: 'span',
            errorClass: 'help-inline',
            focusInvalid: false,
            rules: {
                state: {
                    required: true
                },
                articulo: {
                    required: true
                },
                cantidad: {
                    required: true
                },
                desc: {
                    required: true
                },
            },
            messages: {
                articulo: {
                    required: "Please provide a valid email.",
                },
                state: {
                    required: "Please specify a password.",
                },
                
            },
            invalidHandler: function(event, validator) { //display error alert on form submit   
                $('.alert-error', $('.login-form')).show();
            },
            highlight: function(e) {
                $(e).closest('.control-group').removeClass('success').addClass('error');
            },
            success: function(e) {
                $(e).closest('.control-group').removeClass('error').addClass('success');
                $(e).remove();
            },
            errorPlacement: function(error, element) {
                if (element.is(':checkbox') || element.is(':radio')) {
                    var controls = element.closest('.controls');
                    if (controls.find(':checkbox,:radio').length > 1)
                        controls.append(error);
                    else
                        error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                }
                else if (element.is('.select2')) {
                    error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                }
                else if (element.is('.chzn-select')) {
                    error.insertAfter(element.siblings('[class*="chzn-container"]:eq(0)'));
                }
                else
                    error.insertAfter(element);
            },
            submitHandler: function(form) {
                alert('submit');
            },
            invalidHandler: function(form) {
            }
        });




        $('#modal-wizard .modal-header').ace_wizard();
        $('#modal-wizard .wizard-actions .btn[data-dismiss=modal]').removeAttr('disabled');
    })
</script>