<form id="formborrar" method="post" action="<?php echo $this->formBorrar->getAction(); ?>">

<?php echo $this->formBorrar->id; ?> 
<div  tabindex="-1">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="red bigger">Confirme borrar este articulo</h4>
        </div>
    
    <div class="modal-footer">
            
            <button style="margin-top: 34px;" class="btn btn-small" data-dismiss="modal">
                <i class="icon-remove"></i>
                Cancelar
            </button>

            <button id="submit" style="margin-top: 34px;" type="submit" class="btn btn-small btn-primary">
                <i class="icon-ok"></i>
               Borrar
            </button>
    </div>
</div>
</form>

<script type="text/javascript">
    $(function() {
       
      
       $('#formborrar').submit(function() {
             $('#submit').attr("disabled", "disabled");
        });
     
     });
</script>