<div class="space-6"></div>

<div  class="row-fluid">
    <div class="span10 offset1">
        <div id="print" class="widget-box transparent invoice-box">
            <div class="widget-header widget-header-large">
                <h3 class="grey lighter pull-left position-relative">
                    <i class="icon-leaf green"></i>
                    Hoja de Pedido
                </h3>

                <div class="widget-toolbar no-border invoice-info">
                    <span class="invoice-info-label">Pedido:</span>
                    <span class="red">#<?php echo $this->pedido->idpedido ?></span>

                    <br>
                    <span class="invoice-info-label">Creado:</span>
                    <span class="blue"><?php echo $this->pedido->create_at ?></span>
                </div>

                <div class="widget-toolbar hidden-480">
                    <a href="#" onclick="javascript:printDiv('print')">
                        <i class="icon-print"></i>
                    </a>
                </div>
            </div>

            <div class="widget-body">
                <div class="widget-main padding-2">
                    <div class="row-fluid">
                        <div  class="row-fluid dheader">
                            <div  style="float: left; width: 50%" >
                               <div class="row-fluid">
                                    <div class="span6 label label-large label-info arrowed-in arrowed-right">
                                        <b>Información del Cliente </b>
                                    </div>
                                </div>
                                <div >
                                    <ul class="unstyled spaced">
                                        <li>
                                            <i class="icon-caret-right blue"></i>
                                            <b>Rif : </b><?php echo $this->pedido->rif ?>
                                        </li>

                                        <li>
                                            <i class="icon-caret-right blue"></i>
                                            <b>Razon : </b><?php echo $this->pedido->cdes?>
                                        </li>

                                        <li>
                                            <i class="icon-caret-right blue"></i>
                                            <b>Contacto : </b><?php echo $this->pedido->representante?>
                                        </li>

                                        <li>
                                            <i class="icon-caret-right blue"></i>
                                           <b>telf : </b><?php echo $this->pedido->telf?>
                                        </li>
                                        <li>
                                            <i class="icon-caret-right blue"></i>
                                           <b>email : </b><?php echo $this->pedido->email?>
                                        </li>

                                     

                                        
                                    </ul>
                                </div>
                            </div><!--/span-->

                            <div style="float: left">
                               <div class="row-fluid">
                                    <div class="span12 label label-large label-success arrowed-in arrowed-right">
                                        <b>Información Vendedor</b>
                                    </div>
                                </div> 

                                <div >
                                    <ul class="unstyled spaced">
                                        <li>
                                            <i class="icon-caret-right green"></i>
                                           <b>Codigo : </b><?php echo $this->pedido->vcod?>
                                        </li>

                                        <li>
                                            <i class="icon-caret-right green"></i>
                                            <b>Vendedor : </b><?php echo $this->pedido->nombre?>
                                        </li>

                                        <li>
                                            <i class="icon-caret-right green"></i>
                                             <b>Credito : </b><?php echo $this->pedido->cpdes?>
                                        </li>
                                        <li>
                                            <i class="icon-caret-right green"></i>
                                             <b>Despachar : </b><?php echo $this->pedido->despacho?>
                                        </li>

                                    

                                       
                                    </ul>
                                </div>
                            </div><!--/span-->
                        </div><!--row-->

                      

                       
                            <!----  TABLE ARTICULOS  --->
                             <table  id="sample-table-2" class="table table-striped table-bordered table-hover tdetalle">
                    <thead>


                        <tr>
                            <th class="center">
                                Items
                            </th>
                            <th>Codigo</th>
                            <th>Articulo</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>Descuento</th>
                            <th>Total</th>                      

                           
                        </tr>
                    </thead>


                    <tbody>
                        <?php             
                        $netoFila = 0;
                        $sumaTotalFila[] = 0;
                            ?>    
                        <?php
                        $item = 0;
                        foreach ($this->articulosPedidos as $articulo):
                            $item++;

                            $netoFila = $articulo->precio1 * $articulo->cantidad;
                            $desc = $netoFila * $articulo->desc;
                            $descFila = $desc / 100;
                            $totalFila = $netoFila - $descFila;

                            $sumaTotalFila[] = $totalFila;
                            ?>
                            <tr>
                                <td class="center"  >
                                    <?php echo $item ?>
                                </td>

                                <td  >
                                    <?php echo $articulo->cod; ?> 
                                </td>
                                <td  >
                                    <?php echo $articulo->descripcion; ?>
                                </td >
                                <td  >
                                    <b><?php echo number_format($articulo->precio1, 0, ',', '.'); ?></b>
                                </td>
                                <td  >
                                    <?php echo $articulo->cantidad . ' UND  -   ' . number_format($netoFila, 0, ',', '.').' Bfs'; ?>
                                </td>
                                <td  >
                                    <?php echo $articulo->desc . '% - ' . number_format($descFila, 2, ',', '.'). ' BsF'; ?>
                                </td>
                                <td style="text-align: right"  >
                                    <b><?php echo number_format($totalFila, 2, ',', '.') . ' Bsf'; ?></b>   
                                </td>
                                <!-- Columna de  Opciones -->
                                
                            </tr>
                        <?php endforeach; ?>

                    </tbody>
                    <tfoot>
                        <?php
                        $subtotal = array_sum($sumaTotalFila);

                        $ivaSubtotal = $subtotal * 12;
                        $iva = $ivaSubtotal / 100;

                        $totalFila = $subtotal + $iva;
                        ?>
                        <tr>                                
                            <th colspan="6" style="text-align: right"><span class="label label-info arrowed arrowed-righ">Subtotal : </span></th>
                            <th class="text-info" style="text-align: right"> 
                                <span style="font-size: 10px;"> 
                                    <b>
                                <?php
                                    echo number_format($subtotal, 2, ',', '.') . ' BsF';
                                ?>
                                    </b>
                                </span>
                            </th>                      
                           
                        </tr>
                        <tr>                                
                            <th colspan="6" style="text-align: right"><span class="label label-grey arrowed-in">IVA 12%:</span></th>
                            <th class="grey" style="text-align: right"> 
                                <span  style="font-size: 10px;"> 
                                    <?php
                                    echo number_format($iva, 2, ',', '.') . ' BsF';
                                    ?>
                                </span>
                            </th>                      
                           
                        </tr>
                        <tr>                                
                            <th colspan="6" class="text-success" style="text-align: right" style="font-size: 10px;">TOTAL A PAGAR:</th>
                            <th class="text-success" style="text-align: right"> 
                                <span  style="font-size: 10px;"> 

                                    <b><?php echo number_format($totalFila, 2, ',', '.') . ' BsF'; ?> </b>              

                                </span>
                            </th>                      
                          
                        </tr>

                    </tfoot>
                </table>
                            
                            <!---- END TABLE ARTICULOS  --->
                            
                            
                            
                            
                            
                        

                        <div class="hr hr8 hr-double hr-dotted"></div>

                        <div class="row-fluid">
                            <div class="span5 pull-right">
                                <h4 class="pull-right">
                                    
                                    <span class="red"></span>
                                </h4>
                            </div>
                            <div class="span7 pull-left" style="font-size: 11px"> Observacion</div>
                        </div>

                        <div class="space-6"></div>

                        <div class="row-fluid">
                            <div class="span12 well" style="font-size: 10px">
                              <?php echo $this->pedido->pdes?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script language="javascript" type="text/javascript">
        function printDiv(divID) {
            //Get the HTML of div
            var divElements = document.getElementById(divID).innerHTML;
            //Get the HTML of whole page
            var oldPage = document.body.innerHTML;

            //Reset the page's HTML with div's HTML only
            document.body.innerHTML = 
              "<html><head><title></title></head><body>" + 
              divElements + "</body>";

            //Print Page
            window.print();

            //Restore orignal HTML
            document.body.innerHTML = oldPage;
          
        }
    </script>