<div class="page-header position-relative">
    <h1>
        Pedidos
        <small>
            <i class="icon-double-angle-right"></i>
            Modulo Ventas 
        </small>
    </h1>
</div><!--/.page-header-->
<div class="widget-box">

    <div class="widget-header widget-header-blue widget-header-flat">
        <h4 class="lighter green">Editar Pedido</h4>
    </div>

    <div class="widget-body">
        <div class="widget-main">
            <?php if ($this->error): ?>
                <?php echo $this->errorBox($this->error); ?>
            <?php endif; ?>
            <form id="pedido" method="post" action="<?php echo $this->baseUrl . $this->formDatosClientes->getAction(); ?>" class="form-horizontal">

                <div class="row-fluid">

                    <div class="span7">
                        <label><h4>Cliente</h4>
                            <?php echo $this->formDatosClientes->cliente; ?>
                        </label>
                    </div>
                    <div class="span3">
                        <label><h4>Cond. Pago</h4>
                            <?php echo $this->formDatosClientes->condPago; ?>
                        </label>
                    </div>
                    <div class="span2">
                        <label><h4>Creado</h4>
                            <?php echo $this->formDatosClientes->fechaCreado; ?>
                        </label>
                    </div>

                </div>
                <div class="row-fluid">
                    <div class="span7">
                        <label ><h4>Vendedor</h4>
                            <?php echo $this->formDatosClientes->vendedor; ?>
                        </label>
                    </div>
                    <div class="span3">
                        <label ><h4>Status</h4>
                            <?php echo $this->formDatosClientes->status; ?>
                        </label>
                    </div>
                    <div class="span2">
                        <label><h4>Despacho</h4>
                            <?php echo $this->formDatosClientes->fechaDespacho; ?>
                        </label>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span7">
                        <label ><h4>Descripción</h4>
                            <?php echo $this->formDatosClientes->descripcion; ?>
                        </label>
                    </div>
                    <div class="span5">
                        <label >
                            <div class="infobox infobox-red  ">
                                <div class="infobox-icon">
                                    <i class="icon-barcode"></i>
                                </div>
                                <div class="infobox-data">
                                    <span class="infobox-data-number">
                                        <?php echo $this->idpedido;?>
                                    </span>
                                    <div class="infobox-content">N° del Pedido</div>
                                </div>
                            </div>
                        </label>
                    </div>
                </div>

                <div class="form-actions wizard-actions">                    
                    <button type="reset" class="btn">
                        <i class="icon-undo bigger-110"></i>
                        Reset
                    </button>
                    &nbsp; &nbsp; &nbsp;
                    <button type="submit" class="btn btn-medium btn-success">

                        Guardar y Cargar articulos
                        <i class="icon-arrow-right icon-on-right"></i>
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>