


<form id="validation-form" method="post" action="<?php echo $this->formDatosArticulos->getAction(); ?>">
<?php echo $this->formDatosArticulos; ?>
    
    
    <div class="modal-footer">
            <div class="infobox infobox-red" style="float:left">
                <div class="infobox-icon">
                    <i class="icon-barcode"></i>
                </div>
                <div class="infobox-data">
                    <span class="infobox-data-number">
                        <?php echo $this->idpedido; ?>
                    </span>
                    <div class="infobox-content">N° del Pedido</div>
                </div>
            </div>
            <button style="margin-top: 34px;" class="btn btn-small" data-dismiss="modal">
                <i class="icon-remove"></i>
                Cancelar
            </button>

            <button style="margin-top: 34px;" class="btn btn-small btn-primary">
                <i class="icon-ok"></i>
                Guardar Articulo
            </button>
        </div>
</form>



<?php echo $this->headScript() ?>
<!--inline scripts related to this page-->

<script type="text/javascript">
    $(function() {

        $(".chzn-select").chosen({width: "100%"});

        //$('#cantidad').ace_spinner({value: 1, min: 1, max: 1000, step: 1, icon_up: 'icon-plus', icon_down: 'icon-minus', btn_up_class: 'btn-success', btn_down_class: 'btn-danger'}).css('width', '90%');
        //$('#desc').ace_spinner({disabled: true, value: 0, min: 0, max: 5, step: 5, icon_up: 'icon-plus', icon_down: 'icon-minus', btn_up_class: 'btn-success', btn_down_class: 'btn-danger'}).css('width', '90%');

        $(".select2").css('width', '100%').select2({allowClear: true})
                .on('change', function() {
            $(this).closest('form').validate().element($(this));
        });

        //documentation : http://docs.jquery.com/Plugins/Validation/validate

        $('#validation-form').validate({
            errorElement: 'span',
            errorClass: 'help-inline',
            focusInvalid: false,
            rules: {
               
                idarticulo: {
                    required: true
                },
                cantidad: {
                    required: true
                },
                desc: {
                    required: true
                },
            },
            messages: {
                idarticulo: {
                    required: "Seleccione un Articulo",
                },
               
            },
            invalidHandler: function(event, validator) { //display error alert on form submit   
                $('.alert-error', $('.login-form')).show();
            },
            highlight: function(e) {
                $(e).closest('.control-group').removeClass('success').addClass('error');
            },
            success: function(e) {
                $(e).closest('.control-group').removeClass('error').addClass('success');
                $(e).remove();
            },
            errorPlacement: function(error, element) {
                if (element.is(':checkbox') || element.is(':radio')) {
                    var controls = element.closest('.controls');
                    if (controls.find(':checkbox,:radio').length > 1)
                        controls.append(error);
                    else
                        error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                }
                else if (element.is('.select2')) {
                    error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                }
                else if (element.is('.chzn-select')) {
                    error.insertAfter(element.siblings('[class*="chzn-container"]:eq(0)'));
                }
                else
                    error.insertAfter(element);
            },
            submitHandler: function(form) {
                //alert('submit');
                form.submit();
            },
            invalidHandler: function(form) {
            }
        });
       
    })
</script>