<div class="page-header position-relative">
    <h1>
        Pedidos
        <small>
            <i class="icon-double-angle-right"></i>
            Modulo Ventas 
        </small>
    </h1>
</div><!--/.page-header-->
<div class="widget-box">

    <div class="widget-header widget-header-blue widget-header-flat">
        <h3 class="lighter green">Editar Pedido</h3>
    </div>

    <div class="widget-body">
        <div class="widget-main">
            <?php if ($this->error): ?>
                <?php echo $this->errorBox($this->error); ?>
            <?php endif; ?>
            <form id="pedido" method="post" action="<?php echo $this->baseUrl . $this->formDatosClientes->getAction(); ?>" class="form-horizontal">


                <div class="row-fluid">

                    <div class="span7">
                        <label><h4>Cliente</h4>
                            <?php echo $this->formDatosClientes->cliente; ?>
                        </label>
                    </div>
                    <div class="span3">
                        <label><h4>Cond. Pago</h4>
                            <?php echo $this->formDatosClientes->condPago; ?>
                        </label>
                    </div>
                    <div class="span2">
                        <label><h4>Creado</h4>
                            <?php echo $this->formDatosClientes->fechaCreado; ?>
                        </label>
                    </div>

                </div>
                <div class="row-fluid">
                    <div class="span7">
                        <label ><h4>Vendedor</h4>
                            <?php echo $this->formDatosClientes->vendedor; ?>
                        </label>
                    </div>
                    <div class="span3">
                        <label ><h4>Status</h4>
                            <?php echo $this->formDatosClientes->status; ?>
                        </label>
                    </div>
                    <div class="span2">
                        <label><h4>Despacho</h4>
                            <?php echo $this->formDatosClientes->fechaDespacho; ?>
                        </label>
                    </div>
                </div>

                <div class="row-fluid">
                     <div class="span6">
                        <label ><h4>Descripción</h4>
                            <?php echo $this->formDatosClientes->descripcion; ?>
                        </label>
                    </div>
                    <div class="span4 text-right" style="padding: 5px">

                        <div class="infobox infobox-red  ">
                            <div class="infobox-icon">
                                <i class="icon-barcode"></i>
                            </div>
                            <div class="infobox-data">
                                <span class="infobox-data-number">
                                    <?php echo $this->idpedido; ?>
                                </span>
                                <div class="infobox-content">N° del Pedido</div>
                            </div>
                        </div>

                    </div>
                   
                    <div class="span1">
                                                                      
                            <button type="submit" class="btn btn-small btn-success">

                                Guardar
                                <i class="icon-arrow-right icon-on-right"></i>
                            </button>
                       
                    </div>

                </div>
            </form>
                <?php             
                        $netoFila = 0;
                        $sumaTotalFila[] = 0;
                ?>    
           
            <div id="art" class="row-fluid">
                <h4 class="header smaller lighter orange"><strong>Articulos del pedido</strong></h4>
                <button class="btn btn-small btn-primary " <?php 
                if ($this->itemsArticulos >= 40) {
                echo 'disabled="disabled"';
                } ?>  id="agregar-art" data-toggle="modal-ajax" href="<?php echo $this->baseUrl('/ventas/pedidos/agregararticulo/id/') . $this->idpedido ?>" type="button" >
                    <i class="icon-plus-sign-alt"></i>   
                    Agregar Articulo
                </button>&nbsp;&nbsp;&nbsp;
                <?php if ($this->itemsArticulos >= 40): ?>
                    <span class="text-error">Los Pedidos solo aceptan <b>40 items</b></span>
                <?php else: ?>
                    <span class="text-success">
                        items Agregados
                        <b><?php echo $this->itemsArticulos; ?></b>
                        de 40   
                    </span>
                <?php endif; ?>



                <table id="sample-table-2" class="table table-striped table-bordered table-hover">
                    <thead>


                        <tr>
                            <th class="center">
                                Items
                            </th>
                            <th>Codigo</th>
                            <th>Articulo</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>Descuento</th>
                            <th>Total</th>                      

                            <th></th>
                        </tr>
                    </thead>


                    <tbody>
                        
                        <?php
                        $item = 0;
                        foreach ($this->articulosPedidos as $articulo):
                            $item++;

                            $netoFila = $articulo->precio1 * $articulo->cantidad;
                            $desc = $netoFila * $articulo->desc;
                            $descFila = $desc / 100;
                            $totalFila = $netoFila - $descFila;

                            $sumaTotalFila[] = $totalFila;
                            ?>
                            <tr>
                                <td class="center">
                                    <?php echo $item ?>
                                </td>

                                <td>
                                    <?php echo $articulo->cod; ?> 
                                </td>
                                <td>
                                    <?php echo $articulo->descripcion; ?>
                                </td>
                                <td >
                                    <b><?php echo number_format($articulo->precio1, 0, ',', '.'); ?></b>
                                </td>
                                <td >
                                    <?php echo $articulo->cantidad . ' U  -   ' . number_format($netoFila, 0, ',', '.'); ?>
                                </td>
                                <td >
                                    <?php echo $articulo->desc . '% - ' . number_format($descFila, 2, ',', '.'); ?>
                                </td>
                                <td style="text-align: right" >
                                    <b><?php echo number_format($totalFila, 2, ',', '.') . ' Bsf'; ?></b>   
                                </td>
                                <!-- Columna de  Opciones -->
                                <td class="td-actions">
                                    <div class="hidden-phone visible-desktop action-buttons">
                                        <a class="blue" href="#">
                                            <i class="icon-zoom-in bigger-130"></i>
                                        </a>

                                        <button type="button" data-toggle="modal-ajax" class="btn green btn-link" href="<?php echo $this->baseUrl('/ventas/pedidos/editararticulo/id/').$articulo->idpha;?>">
                                            <i class="icon-pencil bigger-130 green"></i>
                                        </button>

                                        <button data-toggle="modal-ajax" class="btn red btn-link" href="<?php echo $this->baseUrl('/ventas/pedidos/borrararticulo/id/').$articulo->idpha;?>">
                                            <i class="icon-trash red bigger-130"></i>
                                        </button>
                                    </div>

                                  
                                </td>
                            </tr>
                        <?php endforeach; ?>

                    </tbody>
                    <tfoot>
                        <?php
                        $subtotal = array_sum($sumaTotalFila);

                        $ivaSubtotal = $subtotal * 12;
                        $iva = $ivaSubtotal / 100;

                        $totalFila = $subtotal + $iva;
                        ?>
                        <tr>                                
                            <th colspan="6" style="text-align: right"><span class="label label-info arrowed arrowed-righ">Subtotal : </span></th>
                            <th class="text-info" style="text-align: right"> 
                                <span style="font-size: 16px"> 
                                    <b>
                                <?php
                                    echo number_format($subtotal, 2, ',', '.') . ' BsF';
                                ?>
                                    </b>
                                </span>
                            </th>                      
                            <th></th>
                        </tr>
                        <tr>                                
                            <th colspan="6" style="text-align: right"><span class="label label-grey arrowed-in">IVA 12%:</span></th>
                            <th class="grey" style="text-align: right"> 
                                <span style="font-size: 16px"> 
                                    <?php
                                    echo number_format($iva, 2, ',', '.') . ' BsF';
                                    ?>
                                </span>
                            </th>                      
                            <th></th>
                        </tr>
                        <tr>                                
                            <th colspan="6" class="text-success" style="text-align: right">TOTAL A PAGAR:</th>
                            <th class="text-success" style="text-align: right"> 
                                <span style="font-size: 18px"> 

                                    <b><?php echo number_format($totalFila, 2, ',', '.') . ' BsF'; ?> </b>              

                                </span>
                            </th>                      
                            <th></th>
                        </tr>

                    </tfoot>
                </table>

                <button class="btn btn-small btn-primary " <?php 
                if ($this->itemsArticulos >= 40) {
                echo 'disabled="disabled"';
                } ?>  id="agregar-art" data-toggle="modal-ajax" href="<?php echo $this->baseUrl('/ventas/pedidos/agregararticulo/id/') . $this->idpedido ?>" type="button" >
                    <i class="icon-plus-sign-alt"></i>   
                    Agregar Articulo
                </button>&nbsp;&nbsp;&nbsp;
                <?php if ($this->itemsArticulos >= 40): ?>
                    <span class="text-error">Los Pedidos solo aceptan <b>40 items</b></span>
                <?php else: ?>
                    <span class="text-success">
                        items Agregados
                        <b><?php echo $this->itemsArticulos; ?></b>
                        de 40   
                    </span>
                <?php endif; ?>

            </div>             


        </div>
    </div>
</div>

