<div class="page-header position-relative">
    <h1>
        Pedidos
        <small>
            <i class="icon-double-angle-right"></i>
            Modulo Ventas 
        </small>
    </h1>
</div><!--/.page-header-->

<div class="widget-box">

    <div class="widget-header widget-header-blue widget-header-flat">
        <h3 class="lighter green">Lista de Pedidos</h3>
    </div>

    <div class="widget-body">
        <div class="widget-main">

            <div id="art" class="row-fluid">    

            <table id="listapedidos" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="center">
                            Items
                        </th>
                        <th>Nro Pedido</th>
                        <th>Vendedor</th>
                        <th>Status</th>
                        <th>Creado </th>
                        <!--th>Monto Total</th-->


                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    <?php $item = 1;
                    foreach ($this->pedidosLista as $pedido):
                        ?>
                        <tr>
                            <td class="center">
    <?php echo $item++ ?>
                            </td>

                            <td class="center">
                                <b><?php echo $pedido->idpedido ?></b>
                            </td>
                            <td class="">
                                <b><?php echo $pedido->cod . ' | ' . $pedido->nombre ?></b>
                            </td>
                            <td class="center">
                                <b><span class="label label-success">NUEVO</span></b>
                            </td>
                            <!--td class="center">
    <?php echo number_format($pedido->monto_total, 0, ',', '.'); ?>
                            </td-->
                            <td class="center">
    <?php echo $pedido->create_at ?>
                            </td>


                            <!-- Columna de  Opciones -->
                            <td class="td-actions">
                                <div class="hidden-phone visible-desktop action-buttons">
                                    <a class="blue" href="#">
                                        <i class="icon-zoom-in bigger-130"></i>
                                    </a>

                                    <a class="btn green btn-link" href="<?php echo $this->baseUrl('/ventas/pedidos/editar/id/').$pedido->idpedido?>">
                                        <i class="icon-pencil bigger-130 green"></i>
                                    </a>

                                    <button data-toggle="modal-ajax" class="btn red btn-link" href="">
                                        <i class="icon-trash red bigger-130"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
<?php endforeach; ?>
                </tbody>
            </table>
            
            
            </div> 
            
        </div>
    </div>
</div>
